### PR TITLE
Harvest doc edit, massive simplification

### PR DESCRIPTION
**Pull request by PCRyan**
@mjoaris @pablobeefy, look ok?

Massively simplified owing to the killer update delivered by @ReflectiveChimp to provide a dashboard on each chain.

### CODE REVIEW

**Comment by ReflectiveChimp** [comment]
For '5. Look at the strategy contract transactions' - for all the *scan explorers (i.e. all but Avalanche); the 'Events' tab can be used to show the successful harvests only (and other events), where as the 'Transactions' tab may show failed harvests / other transactions. Also for the new CAKE vault which harvests on deposit, those TXs won't show up under the 'Transactions' tab, but the 'Token Txs' tab, so looking at the 'Events' tab is more useful here also.

image

**Comment by mjoaris** [comment]
I think @ReflectiveChimp 's comment is valid. @PCRyan will you want to add this in a new commit?

Also, there lacks a description of which network has to be set in your metamask. Because when you connect to dashboard.beefy.finance , it matters on which chain you are.

**Comment by PCRyan** [comment]
@mjoaris Why do you link to a minimal page here in the docs in this excerpt when we could link directly to dashboard.beefy.finance instead?

No matter which chain you choose, you can easily use Beefy Finance's [Deployed Contract Registry](https://github.com/PCRyan/beefy-docs/blob/patch-2/developers/deployed-contract-registry.md).

**Comment by PCRyan** [comment]
Done, I hope. Gave quick special treatment to Avalanche. @mjoaris @ReflectiveChimp

**Comment by mjoaris** [comment]
👍

**Pull request merged**
